#!/usr/bin/env bash



cd /blogindex.xyz/ || \
    { echo "/blogindex.xyz does not exist"; exit 1; }

echo "Cleaning .test virtual environment"
rm -rf /blogindex.xyz/.test

echo "Creating new .test virtual environment"
python -m venv .test

echo "Activating .test virtual environment"
source .test/bin/activate

echo "Install core requirements"
pip install -r requirements.txt

echo "Running Tests"
if [ "${RUN_ON_CI}" = "drone" ]; then
    PYTHONPATH=. pytest --exitfirst -v --failed-first --cov . --cov-report html --capture=tee-sys

else
    pytest --exitfirst --verbose --failed-first --cov=. --cov-report html
fi

if [ -d "./htmlcov" ]; then
    echo "Copying htmlcov to $RESULTS_COV"
    mv htmlcov "${RESULTS_COV}"
    echo "Symlinking to ${RESULTS_LATEST}"
    cd ${RESULTS_DIR}
    ln -s "${RESULTS_START}" latest
fi

if [ -d "${RESULTS_COV}" ]; then
    echo "results are available at https://results.blogindex.dev/${RESULTS_COV}"
else
    echo "An unknown error has occurred. Coverage Test Results are not available for this test."
fi


echo "$(date +%Y-%m-%d_%H-%M-%S)" | tee ${RESULTS_FINISH}