---
version: '3'

services:

  apitest_db:
    container_name: apitest_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=blogindex
      - POSTGRES_PASSWORD=blogindex
      - POSTGRES_DB=blogindex

  apitest:
    container_name: apitest
    build: .
    image: blogindex/api-test:latest
    command:
      - /loop
    volumes:
      - ${RESULTS_DIR}:/${RESULTS_DIR}
#      - /docker/dev/blogindex.xyz/beardedtek:/blogindex.xyz ##OPTIONAL to run local codebase
    depends_on:
     - apitest_db
    environment:
      - RUN_ON_CI=${RUN_ON_CI:-no}
      - DATABASE_DB=blogindex
      - DATABASE_DB_HOST=apitest_db
      - DATABASE_DB_USER=blogindex
      - DATABASE_DB_PASS=blogindex
      - BLOGINDEX_DEBUG=True
      - BLOGINDEX_LOG_LEVEL=DEBUG
      # These variables can be obtained by messaging @BeardedTek:matrix.org
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
      - AUTH0_ISSUER=${AUTH0_ISSUER}
      - AUTH0_ALGORITHMS=${AUTH0_ALGORITHMS}

      # You must provide eith TEST_KEY or CLIENT_ID and CLIENT_SECRET -- NOT BOTH!
      #- TEST_KEY=${TEST_KEY}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}

      - RESULTS_DIR=${RESULTS_DIR}
      - RESULTS_START=${RESULTS_START}
      - RESULTS_PATH=${RESULTS_PATH}
      - RESULTS_COV=${RESULTS_COV}
      - RESULTS_LOG=${RESULTS_LOG}
      - RESULTS_FINISH=${RESULTS_FINISH}
      - RESULTS_LATEST=${RESULTS_LATEST}
